use emenu;
DELETE FROM Dish_Origin;
DELETE FROM Dish_Ingredient;
DELETE FROM MenuSchedule;
DELETE FROM Unit;

DELETE FROM Dish;
DELETE FROM Ingredient;
DELETE FROM Category;
DELETE FROM Origin;
DELETE FROM ServingHours;

DELIMITER $$
CREATE FUNCTION get_id(
	name VARCHAR(255),
    table_name VARCHAR(255)
)
RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE returned_id INT;
	SET returned_id =
        CASE table_name
            WHEN 'Category' THEN (SELECT id FROM Category WHERE Category.name = name)
            WHEN 'Origin' THEN (SELECT id FROM Origin WHERE Origin.name = name)
            WHEN 'Unit' THEN (SELECT id FROM Unit WHERE Unit.name = name)
            WHEN 'Dish' THEN (SELECT id FROM Dish WHERE Dish.name = name)
            WHEN 'Ingredient' THEN (SELECT id FROM Ingredient WHERE Ingredient.name = name)
            ELSE NULL
        END;

    IF returned_id IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Invalid table name or name not found';
    END IF;

	RETURN (returned_id);
END$$
DELIMITER ;

INSERT INTO Category (name)
VALUES ('Main Course'), ('Appetizer'), ('Dessert');

INSERT INTO Origin (name)
VALUES ('America'), ('China'), ('England'), ('Germany'), ('France'), ('Italy'), ('Japan'), ('Korea'), ('Mexico'), ('Russia'), ('Thailand'), ('Vietnam');

INSERT INTO ServingHours (id, start, end)
VALUES (1, '7:00:00', '11:00:00'), (2, '14:00:00', '24:00:00');

INSERT INTO Unit (name)
VALUES ('g'), ('ml'), ('bottles'), ('bunches'), ('heads'), ('leaves'), ('pieces'), ('sheets');

INSERT INTO Ingredient (name, quantity, import_date, expired_date, unit_id)
VALUES
('Ajitama Egg', 365, '2023-11-6', '2024-04-05', get_id('pieces', 'Unit')),
('Apples', 5100, '2023-01-01', '2024-01-01', get_id('pieces', 'Unit')),
('Avocado', 730, '2023-9-17', '2023-12-23', get_id('g', 'Unit')),
('Bamboo Shoots', 913, '2023-10-18', '2023-12-23', get_id('g', 'Unit')),
('Bay Leaves', 30, '2023-12-27', '2023-12-18', get_id('leaves', 'Unit')),
('Bean Sprouts', 1825, '2023-12-24', '2023-12-19', get_id('g', 'Unit')),
('Beef Broth', 3650, '2023-11-9', '2024-02-14', get_id('ml', 'Unit')),
('Beef Tenderloin', 9120, '2023-12-5', '2023-12-23', get_id('g', 'Unit')),
('Bell Peppers', 36500, '2023-9-26', '2023-12-17', get_id('g', 'Unit')),
('Black Pepper', 1820, '2023-9-6', '2023-12-18', get_id('g', 'Unit')),
('Breadcrumbs', 5470, '2023-9-14', '2024-06-07', get_id('g', 'Unit')),
('Breads', 36500, '2023-9-29', '2024-02-15', get_id('g', 'Unit')),
('Broccoli', 54750, '2023-12-6', '2024-06-01', get_id('g', 'Unit')),
('Brown Sugar', 9125, '2023-10-30', '2024-07-29', get_id('g', 'Unit')),
('Butter', 9125, '2023-12-8', '2024-09-19', get_id('g', 'Unit')),
('Caesar Dressing', 730, '2023-11-12', '2023-12-21', get_id('bottles', 'Unit')),
('Carrots', 7300, '2023-12-6', '2024-07-29', get_id('g', 'Unit')),
('Chashu Pork', 4000, '2023-12-30', '2023-12-21', get_id('g', 'Unit')),
('Chicken Breast', 54750, '2023-11-20', '2025-03-20', get_id('g', 'Unit')),
('Chicken Broth', 3050, '2023-10-5', '2024-02-14', get_id('ml', 'Unit')),
('Chocolate', 200, '2023-01-01', '2024-01-01', get_id('g', 'Unit')),
('Cilantro', 7300, '2023-12-2', '2024-08-03', get_id('g', 'Unit')),
('Cinnamon', 810, '2023-01-01', '2024-01-01', get_id('g', 'Unit')),
('Cocoa Powder', 50, '2023-01-01', '2024-01-01', get_id('g', 'Unit')),
('Coconut Milk', 9125, '2023-11-18', '2024-01-16', get_id('ml', 'Unit')),
('Cornstarch', 9125, '2023-10-2', '2024-01-16', get_id('ml', 'Unit')),
('Crab Sticks', 9125, '2023-12-14', '2024-08-27', get_id('g', 'Unit')),
('Cream Cheese', 4200, '2023-01-01', '2024-01-01', get_id('g', 'Unit')),
('Croutons', 36500, '2023-12-17', '2024-01-16', get_id('g', 'Unit')),
('Cucumber', 36500, '2023-11-21', '2024-07-29', get_id('g', 'Unit')),
('Dashi Broth', 7300, '2023-10-23', '2023-12-23', get_id('g', 'Unit')),
('Diced Tomatoes', 3500, '2023-11-9', '2024-05-12', get_id('ml', 'Unit')),
('Digestive Biscuits', 150, '2023-01-01', '2024-01-01', get_id('g', 'Unit')),
('Dijon Mustard', 3650, '2023-9-11', '2024-10-23', get_id('ml', 'Unit')),
('Dipping Sauce', 14600, '2023-12-4', '2024-03-07', get_id('ml', 'Unit')),
('Dried Oregano', 3650, '2023-11-2', '2024-04-10', get_id('g', 'Unit')),
('Egg Noodles', 9125, '2023-10-7', '2024-08-21', get_id('g', 'Unit')),
('Eggs', 1800, '2023-12-3', '2024-07-05', get_id('pieces', 'Unit')),
('Firm Tofu', 54750, '2023-9-23', '2023-12-21', get_id('g', 'Unit')),
('Flour', 9250, '2023-01-01', '2024-01-01', get_id('g', 'Unit')),
('Frozen Edamame', 3650, '2023-9-28', '2024-08-27', get_id('g', 'Unit')),
('Garlic', 2735, '2023-9-4', '2023-12-18', get_id('g', 'Unit')),
('Gelatin', 2100, '2023-01-01', '2024-01-01', get_id('g', 'Unit')),
('Ginger', 7300, '2023-11-23', '2024-09-25', get_id('g', 'Unit')),
('Green Beans', 3600, '2023-11-9', '2024-05-03', get_id('g', 'Unit')),
('Green Onions', 5470, '2023-12-16', '2023-12-23', get_id('g', 'Unit')),
('Ground Beef', 9150, '2023-11-16', '2023-12-21', get_id('g', 'Unit')),
('Gruyère Cheese', 1825, '2023-12-8', '2024-04-10', get_id('g', 'Unit')),
('Guacamole', 1460, '2023-11-3', '2023-12-23', get_id('g', 'Unit')),
('Honey', 9125, '2023-10-4', '2024-07-29', get_id('ml', 'Unit')),
('Italian Sausage', 1775, '2023-9-24', '2024-07-05', get_id('g', 'Unit')),
('Lasagna Noodles', 9125, '2023-10-19', '2024-04-25', get_id('g', 'Unit')),
('Lemon Juice', 1234, '2023-01-01', '2024-01-01', get_id('g', 'Unit')),
('Lettuce', 1825, '2023-12-27', '2023-12-21', get_id('g', 'Unit')),
('Lime Juice', 1950, '2023-11-30', '2025-01-23', get_id('ml', 'Unit')),
('Lime Wedges', 1825, '2023-9-2', '2023-12-24', get_id('g', 'Unit')),
('Marinara Sauce', 7300, '2023-10-7', '2024-01-17', get_id('g', 'Unit')),
('Mayonnaise', 3650, '2023-10-16', '2024-09-25', get_id('g', 'Unit')),
('Milk', 7150, '2023-01-01', '2024-01-01', get_id('ml', 'Unit')),
('Mint Leaves', 365, '2023-12-13', '2023-12-17', get_id('g', 'Unit')),
('Mixed Tempura Vegetables', 3650, '2023-9-25', '2024-05-03', get_id('g', 'Unit')),
('Mozzarella Cheese', 18250, '2023-12-21', '2023-12-18', get_id('g', 'Unit')),
('Mushrooms', 5475, '2023-10-20', '2023-12-21', get_id('g', 'Unit')),
('Nori Seaweed', 3650, '2023-9-8', '2024-06-01', get_id('g', 'Unit')),
('Oil', 1825, '2023-11-1', '2024-04-05', get_id('ml', 'Unit')),
('Olive Oil', 1825, '2023-10-3', '2024-04-10', get_id('g', 'Unit')),
('Onions', 3650, '2023-12-16', '2023-12-20', get_id('g', 'Unit')),
('Pad Thai Sauce', 5475, '2023-11-12', '2023-12-23', get_id('g', 'Unit')),
('Parmesan Cheese', 18250, '2023-12-26', '2024-07-05', get_id('g', 'Unit')),
('Parmigiano-Reggiano Cheese', 1825, '2023-9-15', '2024-03-07', get_id('g', 'Unit')),
('Pasta', 3600, '2023-9-28', '2023-12-21', get_id('g', 'Unit')),
('Peanut Butter', 1825, '2023-10-30', '2024-04-05', get_id('ml', 'Unit')),
('Peanuts', 36500, '2023-10-7', '2023-12-27', get_id('g', 'Unit')),
('Pickled Ginger', 1300, '2023-10-22', '2024-04-05', get_id('g', 'Unit')),
('Pie Crust', 654, '2023-01-01', '2024-01-01', get_id('pieces', 'Unit')),
('Ramen Broth', 5475, '2023-11-18', '2023-12-23', get_id('g', 'Unit')),
('Ramen Noodles', 2750, '2023-9-20', '2024-05-03', get_id('ml', 'Unit')),
('Red Chili Flakes', 1825, '2023-9-15', '2023-12-21', get_id('g', 'Unit')),
('Red Chili Peppers', 750.00, '2023-9-19', '2023-12-21', get_id('g', 'Unit')),
('Red Curry Paste', 1500.00, '2023-10-5', '2023-12-23', get_id('g', 'Unit')),
('Red Onion', 5000.00, '2023-11-28', '2023-12-21', get_id('g', 'Unit')),
('Rice Noodles', 2000.00, '2023-11-30', '2024-06-01', get_id('g', 'Unit')),
('Rice Paper Wrappers', 3000.00, '2023-12-18', '2024-05-03', get_id('sheets', 'Unit')),
('Rice Vinegar', 3000.00, '2023-12-12', '2024-06-01', get_id('ml', 'Unit')),
('Rice', 7500.00, '2023-11-16', '2023-12-23', get_id('g', 'Unit')),
('Ricotta Cheese', 1500.00, '2023-9-3', '2024-06-07', get_id('g', 'Unit')),
('Romaine Lettuce', 2000.00, '2023-9-4', '2024-06-07', get_id('heads', 'Unit')),
('Salmon', 3000.00, '2023-11-16', '2023-12-21', get_id('g', 'Unit')),
('Salt', 1000.00, '2023-12-3', '2024-02-18', get_id('g', 'Unit')),
('Scallions', 80.00, '2023-12-25', '2023-12-17', get_id('bunches', 'Unit')),
('Sea Salt', 500.00, '2023-9-2', '2024-10-23', get_id('g', 'Unit')),
('Sesame Oil', 3000.00, '2023-11-24', '2024-05-03', get_id('ml', 'Unit')),
('Sesame Seeds', 4500.00, '2023-10-11', '2025-01-23', get_id('g', 'Unit')),
('Shaoxing Wine', 850.00, '2023-9-14', '2024-05-03', get_id('ml', 'Unit')),
('Shredded Lettuce', 3000.00, '2023-10-16', '2024-04-14', get_id('g', 'Unit')),
('Shrimp', 750.00, '2023-11-14', '2024-08-27', get_id('g', 'Unit')),
('Sour Cream', 1500.00, '2023-12-12', '2024-06-10', get_id('g', 'Unit')),
('Soy Sauce', 3000.00, '2023-9-9', '2024-01-16', get_id('ml', 'Unit')),
('Spaghetti', 1500.00, '2023-12-17', '2024-09-01', get_id('g', 'Unit')),
('Sriracha', 750.00, '2023-10-16', '2024-08-27', get_id('g', 'Unit')),
('Strawberries', 6300, '2023-01-01', '2024-01-01', get_id('g', 'Unit')),
('Sugar', 4150, '2023-01-01', '2024-01-01', get_id('g', 'Unit')),
('Sushi Rice', 3000.00, '2023-12-13', '2024-05-03', get_id('g', 'Unit')),
('Taco Seasoning', 1600.00, '2023-10-3', '2024-02-18', get_id('g', 'Unit')),
('Tempura Batter', 4500.00, '2023-9-28', '2025-02-21', get_id('ml', 'Unit')),
('Tempura Dipping Sauce', 750.00, '2023-10-2', '2023-12-23', get_id('g', 'Unit')),
('Thyme', 30.00, '2023-12-3', '2024-10-17', get_id('bunches', 'Unit')),
('Tofu Scrambles', 3000.00, '2023-10-21', '2023-12-21', get_id('g', 'Unit')),
('Tofu', 2500.00, '2023-11-11', '2024-03-07', get_id('g', 'Unit')),
('Tomato Paste', 750.00, '2023-11-1', '2024-03-12', get_id('g', 'Unit')),
('Tomato Sauce', 2250.00, '2023-12-25', '2023-12-23', get_id('g', 'Unit')),
('Tomatoes', 6000, '2023-9-19', '2023-12-23', get_id('g', 'Unit')),
('Tortilla Chips', 2250.00, '2023-9-4', '2024-09-25', get_id('g', 'Unit')),
('Tortillas', 3500.00, '2023-12-24', '2024-03-16', get_id('g', 'Unit')),
('Tuna', 7500.00, '2023-10-28', '2023-12-19', get_id('g', 'Unit')),
('Udon Noodles', 6750.00, '2023-10-6', '2024-06-01', get_id('ml', 'Unit')),
('Vanilla Extract', 4231, '2023-01-01', '2024-01-01', get_id('ml', 'Unit')),
('Vegetable Broth', 4500.00, '2023-12-24', '2024-06-01', get_id('g', 'Unit')),
('Vermicelli Noodles', 4500.00, '2023-9-3', '2023-12-23', get_id('g', 'Unit')),
('Wasabi Paste', 900.00, '2023-10-13', '2024-09-25', get_id('g', 'Unit')),
('Worcestershire Sauce', 3600.00, '2023-11-13', '2024-08-03', get_id('g', 'Unit')),
('Yellowtail', 11000, '2023-10-11', '2023-12-17', get_id('g', 'Unit'));

INSERT INTO Dish (name, price, category_id)
VALUES
('Spaghetti Bolognese', 15.99, get_id('Main Course', 'Category')),
('Chicken Tacos', 12.50, get_id('Main Course', 'Category')),
('Stir-Fried Tofu with Vegetables', 13.99, get_id('Main Course', 'Category')),
('Sushi Platter', 20.00, get_id('Main Course', 'Category')),
('French Onion Soup', 7.99, get_id('Main Course', 'Category')),
('Chicken Parmesan', 16.99, get_id('Main Course', 'Category')),
('Lasagna', 14.99, get_id('Main Course', 'Category')),
('Beef Stroganoff', 18.99, get_id('Main Course', 'Category')),
('Kung Pao Chicken', 13.99, get_id('Main Course', 'Category')),
('General Tso\'s Chicken', 14.50, get_id('Main Course', 'Category')),
('California Roll', 12.99, get_id('Main Course', 'Category')),
('Rainbow Roll', 13.99, get_id('Main Course', 'Category')),
('Tempura Udon', 10.99, get_id('Main Course', 'Category')),
('Ramen', 12.50, get_id('Main Course', 'Category')),
('Caesar Salad', 9.99, get_id('Appetizer', 'Category')),
('Guacamole with Chips', 8.50, get_id('Appetizer', 'Category')),
('Edamame', 6.99, get_id('Appetizer', 'Category')),
('Spring Rolls', 5.50, get_id('Appetizer', 'Category')),
('Thai Peanut Curry', 8.99, get_id('Appetizer', 'Category')),
('Pad Thai', 10.99, get_id('Appetizer', 'Category')),
('Chocolate Cake', 12.99, get_id('Dessert', 'Category')),
('Apple Pie', 9.99, get_id('Dessert', 'Category')),
('Strawberry Cheesecake', 11.99, get_id('Dessert', 'Category'));

INSERT INTO Dish_Origin (dish_id, origin_id)
VALUES
(get_id('Spaghetti Bolognese', 'Dish'), get_id('Italy', 'Origin')),
(get_id('Chicken Tacos', 'Dish'), get_id('Mexico', 'Origin')),
(get_id('Chicken Tacos', 'Dish'), get_id('America', 'Origin')),
(get_id('Stir-Fried Tofu with Vegetables', 'Dish'), get_id('China', 'Origin')),
(get_id('Stir-Fried Tofu with Vegetables', 'Dish'), get_id('Japan', 'Origin')),
(get_id('Stir-Fried Tofu with Vegetables', 'Dish'), get_id('Korea', 'Origin')),
(get_id('Sushi Platter', 'Dish'), get_id('Japan', 'Origin')),
(get_id('French Onion Soup', 'Dish'), get_id('France', 'Origin')),
(get_id('Chicken Parmesan', 'Dish'), get_id('Italy', 'Origin')),
(get_id('Chicken Parmesan', 'Dish'), get_id('America', 'Origin')),
(get_id('Lasagna', 'Dish'), get_id('Italy', 'Origin')),
(get_id('Beef Stroganoff', 'Dish'), get_id('Russia', 'Origin')),
(get_id('Kung Pao Chicken', 'Dish'), get_id('China', 'Origin')),
(get_id('General Tso\'s Chicken', 'Dish'), get_id('America', 'Origin')),
(get_id('California Roll', 'Dish'), get_id('America', 'Origin')),
(get_id('Rainbow Roll', 'Dish'), get_id('America', 'Origin')),
(get_id('Tempura Udon', 'Dish'), get_id('Japan', 'Origin')),
(get_id('Ramen', 'Dish'), get_id('Japan', 'Origin')),
(get_id('Caesar Salad', 'Dish'), get_id('Italy', 'Origin')),
(get_id('Caesar Salad', 'Dish'), get_id('Mexico', 'Origin')),
(get_id('Guacamole with Chips', 'Dish'), get_id('Mexico', 'Origin')),
(get_id('Edamame', 'Dish'), get_id('China', 'Origin')),
(get_id('Edamame', 'Dish'), get_id('Japan', 'Origin')),
(get_id('Spring Rolls', 'Dish'), get_id('China', 'Origin')),
(get_id('Spring Rolls', 'Dish'), get_id('Vietnam', 'Origin')),
(get_id('Thai Peanut Curry', 'Dish'), get_id('Thailand', 'Origin')),
(get_id('Pad Thai', 'Dish'), get_id('Thailand', 'Origin')),
(get_id('Chocolate Cake', 'Dish'), get_id('Germany', 'Origin')),
(get_id('Chocolate Cake', 'Dish'), get_id('America', 'Origin')),
(get_id('Apple Pie', 'Dish'), get_id('England', 'Origin')),
(get_id('Apple Pie', 'Dish'), get_id('America', 'Origin')),
(get_id('Strawberry Cheesecake', 'Dish'), get_id('America', 'Origin'));

INSERT INTO Dish_Ingredient (dish_id, ingredient_id)
VALUES
(get_id('Spaghetti Bolognese', 'Dish'),get_id('Peanuts', 'Ingredient')),
(get_id('Spaghetti Bolognese', 'Dish'),get_id('Tomatoes', 'Ingredient')),
(get_id('Spaghetti Bolognese', 'Dish'),get_id('Onions', 'Ingredient')),
(get_id('Spaghetti Bolognese', 'Dish'),get_id('Garlic', 'Ingredient')),
(get_id('Spaghetti Bolognese', 'Dish'),get_id('Ground Beef', 'Ingredient')),
(get_id('Spaghetti Bolognese', 'Dish'),get_id('Beef Broth', 'Ingredient')),
(get_id('Spaghetti Bolognese', 'Dish'),get_id('Tomato Paste', 'Ingredient')),
(get_id('Spaghetti Bolognese', 'Dish'),get_id('Dried Oregano', 'Ingredient')),
(get_id('Spaghetti Bolognese', 'Dish'),get_id('Salt', 'Ingredient')),
(get_id('Spaghetti Bolognese', 'Dish'),get_id('Black Pepper', 'Ingredient')),
(get_id('Spaghetti Bolognese', 'Dish'),get_id('Parmesan Cheese', 'Ingredient')),

(get_id('Chicken Tacos', 'Dish'),get_id('Pasta', 'Ingredient')),
(get_id('Chicken Tacos', 'Dish'),get_id('Chicken Breast', 'Ingredient')),
(get_id('Chicken Tacos', 'Dish'),get_id('Taco Seasoning', 'Ingredient')),
(get_id('Chicken Tacos', 'Dish'),get_id('Tortillas', 'Ingredient')),
(get_id('Chicken Tacos', 'Dish'),get_id('Shredded Lettuce', 'Ingredient')),
(get_id('Chicken Tacos', 'Dish'),get_id('Diced Tomatoes', 'Ingredient')),
(get_id('Chicken Tacos', 'Dish'),get_id('Sour Cream', 'Ingredient')),
(get_id('Chicken Tacos', 'Dish'),get_id('Guacamole', 'Ingredient')),

(get_id('Stir-Fried Tofu with Vegetables', 'Dish'),get_id('Lime Wedges', 'Ingredient')),
(get_id('Stir-Fried Tofu with Vegetables', 'Dish'),get_id('Tofu', 'Ingredient')),
(get_id('Stir-Fried Tofu with Vegetables', 'Dish'),get_id('Soy Sauce', 'Ingredient')),
(get_id('Stir-Fried Tofu with Vegetables', 'Dish'),get_id('Sesame Oil', 'Ingredient')),
(get_id('Stir-Fried Tofu with Vegetables', 'Dish'),get_id('Broccoli', 'Ingredient')),
(get_id('Stir-Fried Tofu with Vegetables', 'Dish'),get_id('Carrots', 'Ingredient')),
(get_id('Stir-Fried Tofu with Vegetables', 'Dish'),get_id('Bell Peppers', 'Ingredient')),
(get_id('Stir-Fried Tofu with Vegetables', 'Dish'),get_id('Ginger', 'Ingredient')),
(get_id('Stir-Fried Tofu with Vegetables', 'Dish'),get_id('Garlic', 'Ingredient')),
(get_id('Stir-Fried Tofu with Vegetables', 'Dish'),get_id('Rice', 'Ingredient')),

(get_id('Sushi Platter', 'Dish'),get_id('Oil', 'Ingredient')),
(get_id('Sushi Platter', 'Dish'),get_id('Sushi Rice', 'Ingredient')),
(get_id('Sushi Platter', 'Dish'),get_id('Nori Seaweed', 'Ingredient')),
(get_id('Sushi Platter', 'Dish'),get_id('Cucumber', 'Ingredient')),
(get_id('Sushi Platter', 'Dish'),get_id('Avocado', 'Ingredient')),
(get_id('Sushi Platter', 'Dish'),get_id('Salmon', 'Ingredient')),
(get_id('Sushi Platter', 'Dish'),get_id('Tuna', 'Ingredient')),
(get_id('Sushi Platter', 'Dish'),get_id('Shrimp', 'Ingredient')),
(get_id('Sushi Platter', 'Dish'),get_id('Wasabi Paste', 'Ingredient')),
(get_id('Sushi Platter', 'Dish'),get_id('Pickled Ginger', 'Ingredient')),

(get_id('French Onion Soup', 'Dish'),get_id('Soy Sauce', 'Ingredient')),
(get_id('French Onion Soup', 'Dish'),get_id('Beef Broth', 'Ingredient')),
(get_id('French Onion Soup', 'Dish'),get_id('Onions', 'Ingredient')),
(get_id('French Onion Soup', 'Dish'),get_id('Butter', 'Ingredient')),
(get_id('French Onion Soup', 'Dish'),get_id('Thyme', 'Ingredient')),
(get_id('French Onion Soup', 'Dish'),get_id('Bay Leaves', 'Ingredient')),
(get_id('French Onion Soup', 'Dish'),get_id('Breads', 'Ingredient')),
(get_id('French Onion Soup', 'Dish'),get_id('Gruyère Cheese', 'Ingredient')),
(get_id('French Onion Soup', 'Dish'),get_id('Salt', 'Ingredient')),

(get_id('Chicken Parmesan', 'Dish'),get_id('Black Pepper', 'Ingredient')),
(get_id('Chicken Parmesan', 'Dish'),get_id('Chicken Breast', 'Ingredient')),
(get_id('Chicken Parmesan', 'Dish'),get_id('Breadcrumbs', 'Ingredient')),
(get_id('Chicken Parmesan', 'Dish'),get_id('Parmesan Cheese', 'Ingredient')),
(get_id('Chicken Parmesan', 'Dish'),get_id('Eggs', 'Ingredient')),
(get_id('Chicken Parmesan', 'Dish'),get_id('Marinara Sauce', 'Ingredient')),
(get_id('Chicken Parmesan', 'Dish'),get_id('Mozzarella Cheese', 'Ingredient')),
(get_id('Chicken Parmesan', 'Dish'),get_id('Spaghetti', 'Ingredient')),
(get_id('Chicken Parmesan', 'Dish'),get_id('Olive Oil', 'Ingredient')),
(get_id('Chicken Parmesan', 'Dish'),get_id('Salt', 'Ingredient')),

(get_id('Lasagna', 'Dish'),get_id('Black Pepper', 'Ingredient')),
(get_id('Lasagna', 'Dish'),get_id('Lasagna Noodles', 'Ingredient')),
(get_id('Lasagna', 'Dish'),get_id('Ricotta Cheese', 'Ingredient')),
(get_id('Lasagna', 'Dish'),get_id('Parmesan Cheese', 'Ingredient')),
(get_id('Lasagna', 'Dish'),get_id('Mozzarella Cheese', 'Ingredient')),
(get_id('Lasagna', 'Dish'),get_id('Ground Beef', 'Ingredient')),
(get_id('Lasagna', 'Dish'),get_id('Italian Sausage', 'Ingredient')),
(get_id('Lasagna', 'Dish'),get_id('Tomato Sauce', 'Ingredient')),
(get_id('Lasagna', 'Dish'),get_id('Onions', 'Ingredient')),
(get_id('Lasagna', 'Dish'),get_id('Garlic', 'Ingredient')),
(get_id('Lasagna', 'Dish'),get_id('Dried Oregano', 'Ingredient')),
(get_id('Lasagna', 'Dish'),get_id('Salt', 'Ingredient')),

(get_id('Beef Stroganoff', 'Dish'),get_id('Black Pepper', 'Ingredient')),
(get_id('Beef Stroganoff', 'Dish'),get_id('Beef Tenderloin', 'Ingredient')),
(get_id('Beef Stroganoff', 'Dish'),get_id('Mushrooms', 'Ingredient')),
(get_id('Beef Stroganoff', 'Dish'),get_id('Onions', 'Ingredient')),
(get_id('Beef Stroganoff', 'Dish'),get_id('Garlic', 'Ingredient')),
(get_id('Beef Stroganoff', 'Dish'),get_id('Beef Broth', 'Ingredient')),
(get_id('Beef Stroganoff', 'Dish'),get_id('Sour Cream', 'Ingredient')),
(get_id('Beef Stroganoff', 'Dish'),get_id('Dijon Mustard', 'Ingredient')),
(get_id('Beef Stroganoff', 'Dish'),get_id('Worcestershire Sauce', 'Ingredient')),
(get_id('Beef Stroganoff', 'Dish'),get_id('Egg Noodles', 'Ingredient')),
(get_id('Beef Stroganoff', 'Dish'),get_id('Butter', 'Ingredient')),
(get_id('Beef Stroganoff', 'Dish'),get_id('Salt', 'Ingredient')),

(get_id('Kung Pao Chicken', 'Dish'),get_id('Black Pepper', 'Ingredient')),
(get_id('Kung Pao Chicken', 'Dish'),get_id('Chicken Breast', 'Ingredient')),
(get_id('Kung Pao Chicken', 'Dish'),get_id('Soy Sauce', 'Ingredient')),
(get_id('Kung Pao Chicken', 'Dish'),get_id('Sesame Oil', 'Ingredient')),
(get_id('Kung Pao Chicken', 'Dish'),get_id('Rice Vinegar', 'Ingredient')),
(get_id('Kung Pao Chicken', 'Dish'),get_id('Honey', 'Ingredient')),
(get_id('Kung Pao Chicken', 'Dish'),get_id('Cornstarch', 'Ingredient')),
(get_id('Kung Pao Chicken', 'Dish'),get_id('Chicken Broth', 'Ingredient')),
(get_id('Kung Pao Chicken', 'Dish'),get_id('Red Chili Peppers', 'Ingredient')),
(get_id('Kung Pao Chicken', 'Dish'),get_id('Scallions', 'Ingredient')),
(get_id('Kung Pao Chicken', 'Dish'),get_id('Peanuts', 'Ingredient')),
(get_id('Kung Pao Chicken', 'Dish'),get_id('Rice', 'Ingredient')),

(get_id('General Tso\'s Chicken', 'Dish'),get_id('Oil', 'Ingredient')),
(get_id('General Tso\'s Chicken', 'Dish'),get_id('Chicken Breast', 'Ingredient')),
(get_id('General Tso\'s Chicken', 'Dish'),get_id('Soy Sauce', 'Ingredient')),
(get_id('General Tso\'s Chicken', 'Dish'),get_id('Shaoxing Wine', 'Ingredient')),
(get_id('General Tso\'s Chicken', 'Dish'),get_id('Rice Vinegar', 'Ingredient')),
(get_id('General Tso\'s Chicken', 'Dish'),get_id('Honey', 'Ingredient')),
(get_id('General Tso\'s Chicken', 'Dish'),get_id('Sriracha', 'Ingredient')),
(get_id('General Tso\'s Chicken', 'Dish'),get_id('Cornstarch', 'Ingredient')),
(get_id('General Tso\'s Chicken', 'Dish'),get_id('Chicken Broth', 'Ingredient')),
(get_id('General Tso\'s Chicken', 'Dish'),get_id('Red Chili Flakes', 'Ingredient')),
(get_id('General Tso\'s Chicken', 'Dish'),get_id('Scallions', 'Ingredient')),
(get_id('General Tso\'s Chicken', 'Dish'),get_id('Sesame Seeds', 'Ingredient')),
(get_id('General Tso\'s Chicken', 'Dish'),get_id('Rice', 'Ingredient')),

(get_id('California Roll', 'Dish'),get_id('Oil', 'Ingredient')),
(get_id('California Roll', 'Dish'),get_id('Sushi Rice', 'Ingredient')),
(get_id('California Roll', 'Dish'),get_id('Nori Seaweed', 'Ingredient')),
(get_id('California Roll', 'Dish'),get_id('Cucumber', 'Ingredient')),
(get_id('California Roll', 'Dish'),get_id('Avocado', 'Ingredient')),
(get_id('California Roll', 'Dish'),get_id('Crab Sticks', 'Ingredient')),
(get_id('California Roll', 'Dish'),get_id('Mayonnaise', 'Ingredient')),
(get_id('California Roll', 'Dish'),get_id('Sesame Seeds', 'Ingredient')),
(get_id('California Roll', 'Dish'),get_id('Wasabi Paste', 'Ingredient')),

(get_id('Rainbow Roll', 'Dish'),get_id('Pickled Ginger', 'Ingredient')),
(get_id('Rainbow Roll', 'Dish'),get_id('Sushi Rice', 'Ingredient')),
(get_id('Rainbow Roll', 'Dish'),get_id('Nori Seaweed', 'Ingredient')),
(get_id('Rainbow Roll', 'Dish'),get_id('Cucumber', 'Ingredient')),
(get_id('Rainbow Roll', 'Dish'),get_id('Avocado', 'Ingredient')),
(get_id('Rainbow Roll', 'Dish'),get_id('Salmon', 'Ingredient')),
(get_id('Rainbow Roll', 'Dish'),get_id('Tuna', 'Ingredient')),
(get_id('Rainbow Roll', 'Dish'),get_id('Yellowtail', 'Ingredient')),
(get_id('Rainbow Roll', 'Dish'),get_id('Shrimp', 'Ingredient')),
(get_id('Rainbow Roll', 'Dish'),get_id('Mayonnaise', 'Ingredient')),
(get_id('Rainbow Roll', 'Dish'),get_id('Sesame Seeds', 'Ingredient')),
(get_id('Rainbow Roll', 'Dish'),get_id('Wasabi Paste', 'Ingredient')),

(get_id('Tempura Udon', 'Dish'),get_id('Pickled Ginger', 'Ingredient')),
(get_id('Tempura Udon', 'Dish'),get_id('Udon Noodles', 'Ingredient')),
(get_id('Tempura Udon', 'Dish'),get_id('Dashi Broth', 'Ingredient')),
(get_id('Tempura Udon', 'Dish'),get_id('Mixed Tempura Vegetables', 'Ingredient')),
(get_id('Tempura Udon', 'Dish'),get_id('Tempura Batter', 'Ingredient')),
(get_id('Tempura Udon', 'Dish'),get_id('Oil', 'Ingredient')),
(get_id('Tempura Udon', 'Dish'),get_id('Tempura Dipping Sauce', 'Ingredient')),

(get_id('Ramen', 'Dish'),get_id('Scallions', 'Ingredient')),
(get_id('Ramen', 'Dish'),get_id('Ramen Noodles', 'Ingredient')),
(get_id('Ramen', 'Dish'),get_id('Ramen Broth', 'Ingredient')),
(get_id('Ramen', 'Dish'),get_id('Chashu Pork', 'Ingredient')),
(get_id('Ramen', 'Dish'),get_id('Ajitama Egg', 'Ingredient')),
(get_id('Ramen', 'Dish'),get_id('Nori Seaweed', 'Ingredient')),
(get_id('Ramen', 'Dish'),get_id('Bamboo Shoots', 'Ingredient')),

(get_id('Caesar Salad', 'Dish'),get_id('Green Onions', 'Ingredient')),
(get_id('Caesar Salad', 'Dish'),get_id('Romaine Lettuce', 'Ingredient')),
(get_id('Caesar Salad', 'Dish'),get_id('Parmigiano-Reggiano Cheese', 'Ingredient')),
(get_id('Caesar Salad', 'Dish'),get_id('Croutons', 'Ingredient')),

(get_id('Guacamole with Chips', 'Dish'),get_id('Caesar Dressing', 'Ingredient')),
(get_id('Guacamole with Chips', 'Dish'),get_id('Avocado', 'Ingredient')),
(get_id('Guacamole with Chips', 'Dish'),get_id('Lime Juice', 'Ingredient')),
(get_id('Guacamole with Chips', 'Dish'),get_id('Red Onion', 'Ingredient')),
(get_id('Guacamole with Chips', 'Dish'),get_id('Cilantro', 'Ingredient')),
(get_id('Guacamole with Chips', 'Dish'),get_id('Salt', 'Ingredient')),

(get_id('Edamame', 'Dish'),get_id('Tortilla Chips', 'Ingredient')),
(get_id('Edamame', 'Dish'),get_id('Frozen Edamame', 'Ingredient')),

(get_id('Spring Rolls', 'Dish'),get_id('Sea Salt', 'Ingredient')),
(get_id('Spring Rolls', 'Dish'),get_id('Rice Paper Wrappers', 'Ingredient')),
(get_id('Spring Rolls', 'Dish'),get_id('Vermicelli Noodles', 'Ingredient')),
(get_id('Spring Rolls', 'Dish'),get_id('Lettuce', 'Ingredient')),
(get_id('Spring Rolls', 'Dish'),get_id('Cucumber', 'Ingredient')),
(get_id('Spring Rolls', 'Dish'),get_id('Mint Leaves', 'Ingredient')),
(get_id('Spring Rolls', 'Dish'),get_id('Shrimp', 'Ingredient')),

(get_id('Thai Peanut Curry', 'Dish'),get_id('Dipping Sauce', 'Ingredient')),
(get_id('Thai Peanut Curry', 'Dish'),get_id('Coconut Milk', 'Ingredient')),
(get_id('Thai Peanut Curry', 'Dish'),get_id('Vegetable Broth', 'Ingredient')),
(get_id('Thai Peanut Curry', 'Dish'),get_id('Red Curry Paste', 'Ingredient')),
(get_id('Thai Peanut Curry', 'Dish'),get_id('Firm Tofu', 'Ingredient')),
(get_id('Thai Peanut Curry', 'Dish'),get_id('Broccoli', 'Ingredient')),
(get_id('Thai Peanut Curry', 'Dish'),get_id('Bell Peppers', 'Ingredient')),
(get_id('Thai Peanut Curry', 'Dish'),get_id('Green Beans', 'Ingredient')),
(get_id('Thai Peanut Curry', 'Dish'),get_id('Peanut Butter', 'Ingredient')),
(get_id('Thai Peanut Curry', 'Dish'),get_id('Soy Sauce', 'Ingredient')),
(get_id('Thai Peanut Curry', 'Dish'),get_id('Brown Sugar', 'Ingredient')),
(get_id('Thai Peanut Curry', 'Dish'),get_id('Lime Juice', 'Ingredient')),
(get_id('Thai Peanut Curry', 'Dish'),get_id('Rice', 'Ingredient')),

(get_id('Pad Thai', 'Dish'),get_id('Cilantro', 'Ingredient')),
(get_id('Pad Thai', 'Dish'),get_id('Rice Noodles', 'Ingredient')),
(get_id('Pad Thai', 'Dish'),get_id('Pad Thai Sauce', 'Ingredient')),
(get_id('Pad Thai', 'Dish'),get_id('Tofu Scrambles', 'Ingredient')),
(get_id('Pad Thai', 'Dish'),get_id('Bean Sprouts', 'Ingredient')),
(get_id('Pad Thai', 'Dish'),get_id('Scallions', 'Ingredient')),
(get_id('Pad Thai', 'Dish'),get_id('Lime Wedges', 'Ingredient')),


(get_id('Chocolate Cake', 'Dish'), get_id('Chocolate', 'Ingredient')),
(get_id('Chocolate Cake', 'Dish'), get_id('Flour', 'Ingredient')),
(get_id('Chocolate Cake', 'Dish'), get_id('Sugar', 'Ingredient')),
(get_id('Chocolate Cake', 'Dish'), get_id('Eggs', 'Ingredient')),
(get_id('Chocolate Cake', 'Dish'), get_id('Butter', 'Ingredient')),
(get_id('Chocolate Cake', 'Dish'), get_id('Cocoa Powder', 'Ingredient')),
(get_id('Chocolate Cake', 'Dish'), get_id('Milk', 'Ingredient')),

(get_id('Apple Pie', 'Dish'), get_id('Apples', 'Ingredient')),
(get_id('Apple Pie', 'Dish'), get_id('Flour', 'Ingredient')),
(get_id('Apple Pie', 'Dish'), get_id('Sugar', 'Ingredient')),
(get_id('Apple Pie', 'Dish'), get_id('Cinnamon', 'Ingredient')),
(get_id('Apple Pie', 'Dish'), get_id('Butter', 'Ingredient')),
(get_id('Apple Pie', 'Dish'), get_id('Lemon Juice', 'Ingredient')),
(get_id('Apple Pie', 'Dish'), get_id('Pie Crust', 'Ingredient')),

(get_id('Strawberry Cheesecake', 'Dish'), get_id('Cream Cheese', 'Ingredient')),
(get_id('Strawberry Cheesecake', 'Dish'), get_id('Sugar', 'Ingredient')),
(get_id('Strawberry Cheesecake', 'Dish'), get_id('Strawberries', 'Ingredient')),
(get_id('Strawberry Cheesecake', 'Dish'), get_id('Butter', 'Ingredient')),
(get_id('Strawberry Cheesecake', 'Dish'), get_id('Digestive Biscuits', 'Ingredient')),
(get_id('Strawberry Cheesecake', 'Dish'), get_id('Gelatin', 'Ingredient')),
(get_id('Strawberry Cheesecake', 'Dish'), get_id('Vanilla Extract', 'Ingredient'));

INSERT INTO MenuSchedule (dish_id, time_id)
VALUES
(get_id('Spaghetti Bolognese', 'Dish'), 2),
(get_id('Chicken Tacos', 'Dish'), 1),
(get_id('Chicken Tacos', 'Dish'), 2),
(get_id('Stir-Fried Tofu with Vegetables', 'Dish'), 1),
(get_id('Sushi Platter', 'Dish'), 2),
(get_id('French Onion Soup', 'Dish'), 1),
(get_id('Chicken Parmesan', 'Dish'), 2),
(get_id('Lasagna', 'Dish'), 1),
(get_id('Lasagna', 'Dish'), 2),
(get_id('Beef Stroganoff', 'Dish'), 1),
(get_id('Beef Stroganoff', 'Dish'), 2),
(get_id('Kung Pao Chicken', 'Dish'), 1),
(get_id('General Tso\'s Chicken', 'Dish'), 1),
(get_id('California Roll', 'Dish'), 1),
(get_id('Rainbow Roll', 'Dish'), 2),
(get_id('Tempura Udon', 'Dish'), 1),
(get_id('Ramen', 'Dish'), 1),
(get_id('Caesar Salad', 'Dish'), 1),
(get_id('Guacamole with Chips', 'Dish'), 1),
(get_id('Edamame', 'Dish'), 1),
(get_id('Spring Rolls', 'Dish'), 1),
(get_id('Thai Peanut Curry', 'Dish'), 1),
(get_id('Pad Thai', 'Dish'), 2),
(get_id('Chocolate Cake', 'Dish'), 2),
(get_id('Apple Pie', 'Dish'), 1),
(get_id('Apple Pie', 'Dish'), 2),
(get_id('Strawberry Cheesecake', 'Dish'), 1);

drop function get_id;